drop table test_plan if exists;
drop table test_suite if exists;

create table test_plan (
    id bigint generated by default as identity,
    uuid varchar(255),
    index integer not null,
    test_suite_id bigint not null,
    nsd_uuid varchar(255),
    nsd binary(255),
    td_uuid varchar(255),
    testd binary(255),
    package_id varchar(255),
    status varchar(255),
    primary key (id)
);

create table test_suite (
    id bigint generated by default as identity,
    uuid varchar(255),
    primary key (id)
);

alter table test_plan
    add constraint FKr3dynl20c9b59u0277wm3n9t9
    foreign key (test_suite_id)
    references test_suite;
