// Copyright (c) 2015 SONATA-NFV, 2019 5GTANGO [, ANY ADDITIONAL AFFILIATION]
// ALL RIGHTS RESERVED.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Neither the name of the SONATA-NFV, 5GTANGO [, ANY ADDITIONAL AFFILIATION]
// nor the names of its contributors may be used to endorse or promote
// products derived from this software without specific prior written
// permission.
//
// This work has been performed in the framework of the SONATA project,
// funded by the European Commission under Grant number 671517 through
// the Horizon 2020 and 5G-PPP programmes. The authors would like to
// acknowledge the contributions of their colleagues of the SONATA
// partner consortium (www.sonata-nfv.eu).
//
// This work has been performed in the framework of the 5GTANGO project,
// funded by the European Commission under Grant number 761493 through
// the Horizon 2020 and 5G-PPP programmes. The authors would like to
// acknowledge the contributions of their colleagues of the 5GTANGO
// partner consortium (www.5gtango.eu).



== V&V Workflow ("Current")

[plantuml,tng-vnv-lcm]
----

@startuml
autonumber

actor "SDK" as SDK
participant "V&V:Gatekeeper" as GKofVNV
participant "Un-Packager" as PKG
database "Catalogue" as CAT
box "V&V LCM" #LightBlue
    participant "Scheduler" as Scheduler
    participant "Workflow Manager" as WFMGR
    participant "TestPlatformManager" as TPMGR
'     database "Local Catalogue" as LOCAT
'     todo we need to add the flows around the LOCAT above
end box

box "V&V TEE" #LightBlue
    participant "Test Execution Engine" as TEE
    participant "Configuration Manager" as TEECM
    participant "Test Driver" as TEETD
    participant "Test Plugin" as TEETP
    database "Repositories" as TRR
end box

box "Service Platform" #LightBlue
    participant "Gatekeeper" as GKofSP
    participant "SP" as SP
end box

SDK -> GKofVNV : upload package
note right : transparent proxy requests via GK was not indicated in this diagram
GKofVNV -> PKG : unpack package
PKG -> CAT : create NS/Test
note right : Catalog is shared between V&V and SP so that you only upload package once
CAT --> PKG : NS/Test UUID
PKG -> GKofVNV : package updated

GKofVNV -> Scheduler : package updated
opt if no package metadata passed in call back
    'Scheduler.discoverAssociatedNssAndTests(PackageMetadata packageMetadata)
    Scheduler -> CAT : read package metadata
end
loop for each NS
      Scheduler -> CAT : get list of Tests applicable to NS
end
loop for each Test
      Scheduler -> CAT : get list of NS applicable to Test
end
Scheduler --> Scheduler : build map of NS'es to Tests


loop for each NS-Tests mapping
        Scheduler -> WFMGR : execute test plan
note right : See method execute(networkService, test)
        WFMGR -> TRR : save test plan: CREATED
        WFMGR -> SP : deploy NS
        WFMGR \\- SP : NS runtime config
        WFMGR -> TRR : update test plan: NS_DEPLOYED
        loop for each Test
              WFMGR -> TRR : create test suite result
              WFMGR -> TEE : run test request (templateId, nsiId)
              TEE -->TEECM : generate config
              TEE <--> TRR : retrieve Test and NSI information
              TEE -> TEE : prepare test
              TEE -> TEE : setup monitor
              TEE -> TEETD : execute test
              TEETD -> TEETP : run test with docker run
              TEETD <-- TEETP : result SUCCESS|FAIL
              TEETD --> TEE : result SUCCESS|FAIL
              TEE -> TEE : gather and store test results
              TEE --> WFMGR : test result: SUCCESS|FAIL
              WFMGR -> TRR : update test plan: test result
        end
        WFMGR -> TRR : update test plan: SUCCESS|FAIL
        WFMGR -> SP : teardown NS
end

@enduml

----
